<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Gallery extends Model
{
    public static function boot()
    {

        

        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($gallery){
            Storage::delete($gallery->image);
        });

    }

    public function property(){
        return $this->belongsTo(Property::class);
    }
}
